services:
  - type: web
    name: rps-flask-app-main
    runtime: python
    plan: free
    autoDeployTrigger: commit
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn rpsapp:app --bind 0.0.0.0:$PORT --workers 1
    healthCheckPath: /
